#!/bin/bash
AWS_FLAGS=""

main () {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --debug | --endpoint-url=* | --no-verify-ssl | --profile=* | \
                --region=* )
                AWS_FLAGS="$AWS_FLAGS \"$1\""; shift;;

            --endpoint-url | --profile | --region )
                AWS_FLAGS="$AWS_FLAGS $1 \"$2\""; shift 2;;

            -- )
                shift;
                break;;

            * )
                echo "Unknown argument $1" 1>&2;
                usage;
                exit 1;;
        esac
    done

    if [[ "$#" -ne 1 ]]; then
        echo "S3 URL not specified" 1>&2;
        usage;
        exit 1;
    fi;

    SLURM_S3_ROOT="$1";

    aws $AWS_FLAGS s3 cp ./scripts/slurm-ec2-bootstrap \
        "$SLURM_S3_ROOT/packages/slurm-ec2-bootstrap";
    aws $AWS_FLAGS s3 cp ./cfntemplates/slurm-cloud.cfn \
        "$SLURM_S3_ROOT/packages/slurm-ec2-bootstrap";
    python ./setup.py sdist
    aws $AWS_FLAGS s3 cp ./dist/slurm-ec2-utils-0.1.tar.gz \
        "$SLURM_S3_ROOT/packages/slurm-ec2-utils-0.1.tar.gz"
}


